// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        url:
            // TODO: check if this has to be changed to pooling/accelerate
            process.env['DIRECT_DATABASE_URL'] ||
            (() => {
                throw new Error('DIRECT_DATABASE_URL is not set');
            })(),
    },
});
